### ISSUE TITLE
CUDA assertion triggered during normalization

### ISSUE THREAD

**Issue by fratajcz** [uma-pi1/kge#169]
Hi all!

I just created a new dataset and started to run a job on it. However, when it begins with epoch 1 it immediately throws a CUDA assert. Here is the error traceback:

```
2021-01-08 13:27:13.140688 [106fcdcc] Trial 00000 failed: RuntimeError('CUDA error: device-side assert triggered')
2021-01-08 13:27:13.140728 [106fcdcc] Aborting search due to failure of trial 00000
2021-01-08 13:27:13.141503 [106fcdcc] Traceback (most recent call last):
2021-01-08 13:27:13.141507 [106fcdcc]   File "/home/fratajcz/kge/kge/cli.py", line 317, in main
2021-01-08 13:27:13.141509 [106fcdcc]     job.run()
2021-01-08 13:27:13.141510 [106fcdcc]   File "/home/fratajcz/kge/kge/job/job.py", line 159, in run
2021-01-08 13:27:13.141512 [106fcdcc]     result = self._run()
2021-01-08 13:27:13.141514 [106fcdcc]   File "/home/fratajcz/kge/kge/job/auto_search.py", line 160, in _run
2021-01-08 13:27:13.141515 [106fcdcc]     self.submit_task(
2021-01-08 13:27:13.141517 [106fcdcc]   File "/home/fratajcz/kge/kge/job/search.py", line 80, in submit_task
2021-01-08 13:27:13.141518 [106fcdcc]     self.ready_task_results.append(task(task_arg, device=self.free_devices[0]))
2021-01-08 13:27:13.141520 [106fcdcc]   File "/home/fratajcz/kge/kge/job/search.py", line 243, in _run_train_job
2021-01-08 13:27:13.141521 [106fcdcc]     raise e
2021-01-08 13:27:13.141523 [106fcdcc]   File "/home/fratajcz/kge/kge/job/search.py", line 196, in _run_train_job
2021-01-08 13:27:13.141525 [106fcdcc]     job.run()
2021-01-08 13:27:13.141526 [106fcdcc]   File "/home/fratajcz/kge/kge/job/job.py", line 157, in run
2021-01-08 13:27:13.141528 [106fcdcc]     f(self)
2021-01-08 13:27:13.141529 [106fcdcc]   File "/home/fratajcz/kge/kge/model/embedder/lookup_embedder.py", line 70, in <lambda>
2021-01-08 13:27:13.141531 [106fcdcc]     job.pre_run_hooks.append(lambda job: self._normalize_embeddings())
2021-01-08 13:27:13.141533 [106fcdcc]   File "/home/fratajcz/kge/kge/model/embedder/lookup_embedder.py", line 60, in _normalize_embeddings
2021-01-08 13:27:13.141534 [106fcdcc]     self._embeddings.weight.data = torch.nn.functional.normalize(
2021-01-08 13:27:13.141536 [106fcdcc]   File "/home/fratajcz/anaconda3/envs/pygeo/lib/python3.8/site-packages/torch/nn/functional.py", line 3788, in normalize
2021-01-08 13:27:13.141537 [106fcdcc]     denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
2021-01-08 13:27:13.141539 [106fcdcc]   File "/home/fratajcz/anaconda3/envs/pygeo/lib/python3.8/site-packages/torch/tensor.py", line 389, in norm
2021-01-08 13:27:13.141541 [106fcdcc]     return torch.norm(self, p, dim, keepdim, dtype=dtype)
2021-01-08 13:27:13.141542 [106fcdcc]   File "/home/fratajcz/anaconda3/envs/pygeo/lib/python3.8/site-packages/torch/functional.py", line 1337, in norm
2021-01-08 13:27:13.141544 [106fcdcc]     return _VF.norm(input, p, _dim, keepdim=keepdim)  # type: ignore
2021-01-08 13:27:13.141546 [106fcdcc] RuntimeError: CUDA error: device-side assert triggered
```

This is accompanied by tons of the following error messages:

```
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [1,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [1,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [1,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

I dont really see why that is happening. During normalization there should be no index error possible. Especially since the embeddings are already normalized during the initialization of the lookup_embedder using the same normalization function without an error. It loads the dataset without any complaint and only dies when running the  job.pre_run_hooks. 

I would be very happy if someone could give me a pointer here.

**Comment by rgemulla** [comment]
Hard to say spontaneously. Perhaps some parameter of the dataset or hyperparameter of the model is set incorrectly, at least that's what's worth checking first. Does this only happen for this "new dataset"? Does everything work on a CPU? Does it work if you solely use training job (i.e., no surrounding search job)?

**Comment by fratajcz** [comment]
Thanks for the swift reply. A hyperparameter is unlikely to be the cause since i used the precise same config for other runs. But now since i created that one new dataset, every new job that I run dies of that same cause, even for other datasets and models. The old ones are still running. However, all I did was create a new dataset.  The problem also occurs on CPU, however, then it is an index error and not a CUDA assert. I also tried it without a surrounding search job but that didn't change a thing.

**Comment by rufex2001** [comment]
Run it on the CPU, it provides a useful error message that should help find
your bug

**Comment by AdrianKs** [comment]
> The problem also occurs on CPU, however, then it is an index error and not a CUDA assert. I also tried it without a surrounding search job but that didn't change a thing.

Can you copy the stack trace of this index error? 

it could be that the dataset is not preprocessed correctly and we are trying to look for an entity id larger than the emedding table in the lookup embedder

**Comment by fratajcz** [comment]
Thanks guys, it turns out the error was completely my own fault, your framework is awesome. I had copied a slightly changed train.txt into the dataset folder. Somehow I didnt rerun the prepocessing script and then the stored IDs didnt match up. Completely rerunning the preprocessing script obviously helped. 

The stack trace of the CPU run pointed out the correct line, shame on you CUDA 😅
